### ISSUE TITLE
bore穿透

### ISSUE THREAD

**Issue by Muska-Ami** [LoCyan-Team/LoCyanFrpPanel#13]
~~当前bore穿透无专用页面，直接放在首页不是很美观，另外用户有自捐节点，应该为bore添加专用页面。~~
bore服务升级改造，暂时暂停服务

页面功能：
- bore穿透服务器列表，包括节点地址，节点网络
- 节点下拉框，用于选择快速生成启动命令
- 节点开放端口范围
- 节点带宽显示

**Comment by XiaMoHuaHuo-CN** [comment]
更新: 页面基本造完了，命令预览还有问题

**Comment by Zhiyuan36** [comment]
建议把列表里“Bore穿透”改为“Bore 穿透”，强迫症表示很难受

**Comment by XiaMoHuaHuo-CN** [comment]
@Zhiyuan36 你改好了我就不改了

**Comment by Muska-Ami** [comment]
fixed
