### ISSUE TITLE
建议通知看过一遍后不再显示

### ISSUE THREAD

**Issue by Zhiyuan36** [LoCyan-Team/LoCyanFrpPanel#16]
建议通知加一个“不再显示”按钮（尽量不要用cooke解决，不然重新登陆又来了），若公告更新再显示。
大概就是这样：
![image](https://github.com/LoCyan-Team/LoCyanFrpPanel/assets/73744019/e06d42d3-ed21-4536-b543-50e90c928210)
然后建议“欢迎”这个模块点击叉叉后自动消失，重新登陆后又出现。

**Comment by Muska-Ami** [comment]
可以写个本地缓存
https://developer.mozilla.org/zh-CN/docs/Web/API/Window/localStorage

**Comment by Daiyangcheng** [comment]
有些人习惯性关闭通知容易错过重要信息，因此不做改动
