### ISSUE TITLE
账户设置模块建议

### ISSUE THREAD

**Issue by Zhiyuan36** [LoCyan-Team/LoCyanFrpPanel#17]
![image](https://github.com/LoCyan-Team/LoCyanFrpPanel/assets/73744019/242d05ee-6dbb-462b-b649-b7055ab745cf)
这张图画了我10min，望采纳

**Comment by Zhiyuan36** [comment]
右下角那个按钮“在所有设备上登陆”写错了，是“在所有设备上登出”

**Comment by Daiyangcheng** [comment]
好的

**Comment by Muska-Ami** [comment]
这个什么时候能做 后端API到现在还没出

**Comment by Daiyangcheng** [comment]
已完成更新
