### ISSUE TITLE
隧道不能编辑和下线

### ISSUE THREAD

**Issue by Ghd-0802** [LoCyan-Team/LoCyanFrpPanel#27]
![image](https://github.com/LoCyan-Team/LoCyanFrpPanel/assets/38886687/ffb64cb4-7859-414b-90d0-3f42caec9d80)
1.编辑隧道时提示,域名未进白名单,只能删除重建
2.隧道出现"router config conflict",无法强制下线服务端,只能更换线路名称和映射域名,希望添加"强制下线"隧道功能

**Comment by Muska-Ami** [comment]
@Daiyangcheng

**Comment by Muska-Ami** [comment]
目前后端暂无API可操作，待LCT团队成员操作

**Comment by Daiyangcheng** [comment]
域名白名单问题会在这周末解决
同时隧道编辑也会恢复

**Comment by Muska-Ami** [comment]
fixed
